### ISSUE TITLE
Why HMS PushKit needs android.permission.REQUEST_INSTALL_PACKAGES

### ISSUE THREAD

**Issue by TurKurT656** [halilozel1903/HuaweiPushKitApp#1]
I've tried this sample and I encountered a problem:
[Why HMS PushKit needs android.permission.REQUEST_INSTALL_PACKAGES](https://stackoverflow.com/questions/65977403/why-hms-pushkit-needs-android-permission-request-install-packages)

**Comment by halilozel1903** [comment]
No. I have tried at the moment. App worked.

<img width="338" alt="Screen Shot 2021-03-16 at 4 57 47 PM" src="https://user-images.githubusercontent.com/22895813/111321200-c38e1c00-8678-11eb-9965-010c81538db9.png">
