### ISSUE TITLE
send notification to subscribe Topic instead token

### ISSUE THREAD

**Issue by Abdelmjid-ASOUAB** [halilozel1903/HuaweiPushKitApp#2]
hey thanks for ur example.
i'm trying to send notification to my users using topic instead of token 
when i send it in HMS console  all things good but it’s not working in the api.
response  said that all's was good but i didn’t got nothing in my phone.
any help please 🙏  
![image](https://user-images.githubusercontent.com/43655719/177566546-335ef5e0-09b0-4bdc-8cc9-e7be52871de6.png)

**Comment by halilozel1903** [comment]
How you doin’, Sometimes notifications take a long time to arrive. @Abdelmjid-ASOUAB

**Comment by Abdelmjid-ASOUAB** [comment]
@halilozel1903 it's not about time. if i got notification from HMS console it's mean  that all configuration is good ?
or i have to add some more for send notifications faction from api ?

**Comment by halilozel1903** [comment]
Nope, It should work as it is. You don't need to add anything extra. @Abdelmjid-ASOUAB
